# Generated by Django 6.0 on 2026-01-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_followus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followus',
            old_name='link',
            new_name='name',
        ),
        migrations.AddField(
            model_name='followus',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
