# Generated by Django 6.0 on 2026-01-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_aboutus_options_alter_followus_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='followus',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='followus',
            name='updated_at',
        ),
    ]
